# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
    gradle-artifactory:
        type: maven-repository
        url: https://api.mapbox.com/downloads/v2/releases/maven
        username: mapbox
        password: ${{secrets.MAPBOX_DOWNLOADS_TOKEN}}
updates:
    -   package-ecosystem: "gradle"
        directory: "/" # Location of package manifests
        registries: "*"
        open-pull-requests-limit: 10
        schedule:
            interval: "weekly"
