package com.weatherxm.ui.common

import com.weatherxm.BuildConfig

object Contracts {
    const val LOADING_DELAY = 200L
    const val EMPTY_VALUE = "?"
    const val DEGREES_MARK = "°"
    const val NOT_AVAILABLE_VALUE = "N/A"
    const val ARG_DEVICE = "device"
    const val ARG_DEVICE_TYPE = "device_type"
    const val ARG_BLE_DEVICE_CONNECTED = "ble_device_connected"
    const val ARG_USER_MESSAGE = "user_message"
    const val ARG_IS_CUSTOM_APPWIDGET_UPDATE = "is_custom_appwidget_update"
    const val ARG_WIDGET_TYPE = "widget_type"
    const val ARG_WIDGET_ID = "widget_id"
    const val ARG_DEVICE_ID = "device_id"
    const val ARG_WIDGET_SHOULD_LOGIN = "widget_should_login"
    const val ARG_WIDGET_SHOULD_SELECT_STATION = "widget_should_select_station"
    const val ARG_WIDGET_ON_LOGGED_IN = "widget_on_logged_in"
    const val ARG_EXPLORER_CELL = "explorer_cell"
    const val ARG_CELL_CENTER = "cell_center"
    const val ARG_OPEN_EXPLORER_ON_BACK = "open_explorer_on_back"
    const val ARG_REWARD = "reward"
    const val ARG_REWARD_DETAILS = "reward_details"
    const val ARG_BOOST_REWARD = "boost_reward"
    const val ARG_WALLET_REWARDS = "wallet_rewards"
    const val ARG_TOKEN_CLAIMED_AMOUNT = "claimed_amount"
    const val ARG_REMOTE_MESSAGE = "remote_message"
    const val ARG_URL = "url"
    const val ARG_TYPE = "type"
    const val ARG_DATE = "date"
    const val ARG_FORECAST_SELECTED_DAY = "forecast_selected_day"
    const val ARG_FCM_TOKEN = "fcm_token"
    const val ARG_DEVICES_REWARDS = "devices_rewards"
    const val ARG_INSTRUCTIONS_ONLY = "instructions_only"
    const val ARG_PHOTOS = "photos"
    const val FILE_PROVIDER_AUTHORITY = "${BuildConfig.APPLICATION_ID}.fileprovider"
    const val ARG_DELETE_ALL_PHOTOS = "delete_all_photos"
    const val ARG_NETWORK_STATS = "network_stats"
    const val ARG_OPEN_STATION_FROM_NOTIFICATION = "open_station_from_notification"
}
