# Detekt configuration override

complexity:
    LongMethod:
        threshold: 80
    TooManyFunctions:
        thresholdInFiles: 15
        thresholdInClasses: 15
        thresholdInInterfaces: 15
        thresholdInObjects: 15
        thresholdInEnums: 15

style:
    MandatoryBracesLoops:
        active: true
    MaxLineLength:
        maxLineLength: 100
    ForbiddenComment:
        comments:
            - FIXME
            - STOPSHIP
    AlsoCouldBeApply:
        active: true
    CanBeNonNullable:
        active: true
    CascadingCallWrapping:
        active: true
    CollapsibleIfStatements:
        active: true
    NullableBooleanCheck:
        active: true
    OptionalUnit:
        active: true
    RedundantExplicitType:
        active: true
    SpacingBetweenPackageAndImports:
        active: true
    UnnecessaryApply:
        active: true
    UnnecessaryBracesAroundTrailingLambda:
        active: true
    UnnecessaryLet:
        active: true
    UnusedImports:
        active: true
    UseDataClass:
        active: true
    UseIfEmptyOrIfBlank:
        active: true
    UseIfInsteadOfWhen:
        active: true
    UseLet:
        active: true

performance:
    CouldBeSequence:
        active: true

naming:
    VariableMaxLength:
        active: true
    VariableMinLength:
        active: true
