publisher:
  name: WeatherXM
  address: ''
  website: https://weatherxm.com
  email: hello@weatherxm.com
  media:
    - purpose: icon
      uri: ./media/publisher.png
app:
  name: WeatherXM
  address: ''
  android_package: com.weatherxm.app.solana
  urls:
    license_url: https://weatherxm.com/terms-conditions/
    copyright_url: https://weatherxm.com/terms-conditions/
    privacy_policy_url: https://weatherxm.com/privacy-policy/
    website: https://weatherxm.com
  media:
    - purpose: icon
      uri: ./media/app_icon.png
release:
  address: ''
  media:
    - purpose: icon
      uri: ./media/app_icon.png
    - purpose: banner
      uri: ./media/banner.png
    - purpose: featureGraphic
      uri: ./media/feature.png
    - purpose: screenshot
      uri: ./media/screen1.png
    - purpose: screenshot
      uri: ./media/screen2.png
    - purpose: screenshot
      uri: ./media/screen3.png
    - purpose: screenshot
      uri: ./media/screen4.png
    - purpose: screenshot
      uri: ./media/screen5.png
  files:
    - purpose: install
      uri: ./files/app-release-solana.apk
  catalog:
    en-US:
      name: WeatherXM
      short_description: Community-Powered Weather
      long_description: |
        WeatherXM is a community-powered project building a more accurate and equitable global weather network. 
        Every forecast you see is the result of collaboration between thousands of contributors around the world.

        This app connects you to that network — and to the mission. It's built for the Solana community, 
        by a community that believes in real-world utility and decentralized infrastructure.

        What You Can Do:
        • View Your Community-Powered Forecast — get reliable, ad-free weather reports sourced from your neighbors and local stations worldwide.
        • See the Network — explore the live map of stations that power the WeatherXM network.

        Are You a Contributor?
        • Manage Your Station — monitor your device’s health, performance, and configuration.
        • Track Your Rewards — see your contribution and how it translates into $WXM token rewards.

        This is your field guide to decentralized weather — and your invitation to help build it.

        Download now and be part of building weather, together.
      new_in_version: |
        - Optimized for Solana Mobile (Seeker) compatibility
        - Updated visuals and UX for crypto-native users
        - Bug fixes and performance improvements
      saga_features: |
        - Optimized dApp experience for Seeker hardware
        - Seamless onboarding with Solana-native UI flows
solana_mobile_dapp_publisher_portal:
  google_store_package: com.weatherxm.app
  testing_instructions: |
    1. Install APK via Solana Mobile dApp Store on your Seeker or Saga phone.
    2. Launch app and allow any requested permissions.
    3. Verify explorer map, station details, and station reward screens load correctly.
    4. Optional: Login with your WeatherXM credentials and walkthrough the entire app.
