name: Build & Firebase Distribution
on:
    push:
        branches: [ develop ]
env:
    ORG_GRADLE_PROJECT_RELEASE_APP_ID: ${{ secrets.RELEASE_APP_ID }}
    ORG_GRADLE_PROJECT_DEBUG_APP_ID: ${{ secrets.DEBUG_APP_ID }}
    ORG_GRADLE_PROJECT_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
    ORG_GRADLE_PROJECT_MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
    ORG_GRADLE_PROJECT_SIGNING_KEYSTORE: ${{ secrets.SIGNING_KEYSTORE }}
    ORG_GRADLE_PROJECT_SIGNING_KEYSTORE_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
    ORG_GRADLE_PROJECT_SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
    ORG_GRADLE_PROJECT_SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
    ORG_GRADLE_PROJECT_FIREBASE_PUBLIC_TEST_GROUP: ${{ secrets.FIREBASE_PUBLIC_TEST_GROUP }}
    ORG_GRADLE_PROJECT_FIREBASE_INTERNAL_TEST_GROUP: ${{ secrets.FIREBASE_INTERNAL_TEST_GROUP }}
    GRADLE_USER_HOME: ${GITHUB_WORKSPACE}/.gradle
    GLOBAL_GRADLE_CACHE: gradle-cache-${GITHUB_REPOSITORY}
jobs:
    debug_distribution:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Gradle package cache
                uses: actions/cache@v2
                with:
                    key: ${{ env.GLOBAL_GRADLE_CACHE }}
                    path: ${{ env.GRADLE_USER_HOME }}
            -   name: Build && Release Debug distribution
                run: |
                    echo "${{ secrets.ENCODED_GOOGLE_SERVICES }}" | base64 -d > ./app/google-services.json
                    mkdir -p publishing
                    echo "${{ secrets.ENCODED_SIGNING_KEYSTORE }}" > debug.keystore.asc
                    gpg -d --passphrase "${{ secrets.ENCODED_SIGNING_KEYSTORE_PASSPHRASE }}" --batch debug.keystore.asc > app/debug.keystore
                    echo "${{ secrets.ENCODED_SERVICE_ACCOUNT }}" | base64 -d > ./ci-service-account.json
                    ./gradlew :app:assembleRemoteDevDebug :app:appDistributionUploadRemoteDevDebug
                    rm ./ci-service-account.json
