name: Auto-assign PR Reviewer

on:
    pull_request:
        types: [ opened, reopened ]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        if: github.actor != 'pavlostze'
        steps:
            -   name: Assign pavlostze as the PR reviewer
                uses: actions/github-script@v7
                with:
                    script: |
                        github.rest.pulls.requestReviewers({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          pull_number: context.payload.pull_request.number,
                          reviewers: ['pavlostze']
                        });
